language: typescript
before_script: npm install
script: npm run build-production
notifications:
  slack:
    secure: D6TPNkiNF6UI+R66M4ngAbVK7pf5rR/aKG4N23QoZpALgTFrz4Lo7L3Z+uC5DelbjUunDfvQxASgDfa3nmSYsSmxbBrlm5uhd1Q3RRwv0rZC50MPI6G/tsEpa5sNIUIQiII4Foj1EpnnDIFVU8BuLhUDsvjJVPEnE6Qtl/50zyDnBOP8okGXQL1jPEqeTInEkcDWZlw2j+YPWYgQgCWi9LfekHCX78TJjQiZdTvBSbplOuk2Vm48Dt/xPPAt7EzG9oXmttxk7n5HcpgvicbS+eR97b3Z4EVmJ7VNkukN4c6FDdne1YiAi2KtfFBcyK2NUCPngZWLryAEH5zD1TkLD7Ry1U3xTGKB1/hhKMMamTmt2qjxBCENodwC8DwsUv/929CTeoJBs7rpkNjKyOXeNzild9LpCCCZVlPACGxKa+Cb46AEWrPD2lJV/u/l+2tuCVicNh83Vk2QqKjF7MwKSuISdbPCcQdbiWuYOUph31essXG4i1Uhlx8xWIqidrRnNAw8gH9/8XZth17Ww76MMU9HmC/BoJootGMYj9dVzVO7N8uH4iPyjZGrVaFvM6lJ0Y+kY1k8uPoLdC3ynnwEqIXzUgzlagzTJfFX4bugjSUy5a2CztCs1pcsw4SHNhhBWbU+xAFCD4zZMZ0yZ5Gaa/XGvlIMt+PVwGilft++cCY=
